# Generated by Django 3.2.9 on 2021-11-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_alter_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='labels',
            field=models.CharField(choices=[('S', 'secondary'), ('P', 'primary'), ('D', 'danger')], default='test description', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='categories',
            field=models.CharField(choices=[('Pet Product', 'Pet Product'), ('Pet', 'Pet')], max_length=15),
        ),
    ]
