# Generated by Django 3.2.9 on 2021-11-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_auto_20211118_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='static/image'),
        ),
    ]
