# Generated by Django 3.2.9 on 2021-12-01 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_itemvariations_variations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemVariations',
            new_name='ItemVariation',
        ),
        migrations.RenameModel(
            old_name='Variations',
            new_name='Variation',
        ),
    ]
